from ROOT import TH1F, TCanvas, kBlue, kRed, TAxis, gStyle, TLegend, TLatex
#To run this macro just run on the terminal
#python2 twodfunction.py
c=TCanvas("c","Function",700,700)
h1=TH1F("histo","My first Histogram",100,-10,10)
h1.FillRandom("gaus",10000)
h1.SetLineColor(kBlue)
h1.SetLineStyle(1)
h1.SetFillColor(kRed)
h1.GetXaxis().SetTitle("1-D Histo")
h1.GetXaxis().CenterTitle()
h1.GetYaxis().SetTitle("Number of Entries")
h1.GetYaxis().CenterTitle()
gStyle.SetOptStat(1111111)
h1.Draw()
legend=TLegend(0.2,0.7,0.43,0.9)
legend.SetHeader("1-D Histogram","C")
legend.AddEntry(h1,"Histogram filled with random numbers","f")
legend.Draw()
latex= TLatex ()
latex.SetTextSize(0.025)
latex.SetTextAlign(13)
latex.DrawLatex(-6,600,"ROOT")
latex.DrawLatex(-6,500,"CERN")
c.Draw()
c.SaveAs("oneDHistopy.png")